### ISSUE TITLE
3-flux : sync XMLHttpRequest warning and GET event errors

### ISSUE THREAD

**Issue by nikrb** [learncodeacademy/react-js-tutorials#12]
Thanx for this resource, just getting started with react and it works straight out the box.
 I'm running the 3-flux example and getting the warning shown below when I click reload. I also see GET errors (send_focus_event, on_focus and on_blur) when using the nav menu.
There aren't any XMLHttpRequest's as far as I can make out. I'd greatly appreciate it if you could tell me where I'm going wrong.
thanx for your time.

```
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
VM509:62 GET http://nikkomsgchannel/e?006d0051005b005a00360031006b0021005e0055005b005300…5500590050003700640052002d004400590008005a002b005c005f0056002d002b0058002e rapport_nikko_send_focus_event @ VM509:62rapport_nikko_on_focus @ VM509:72
VM509:49 GET http://nikkomsgchannel/e?006d0051005b005a00360031006b0021005e0055005b005300…560054002a0036001200240059004600580009002c005e005f0052002c002c005d002e005a rapport_nikko_on_blur @ VM509:49
```

**Comment by nikrb** [comment]
gah apologies, this was due to some trusteer rapport security software that came preloaded on my machine. I actually found the answer in an asp forum. Uninstalled it, don't get the errors anymore. Apologies again for being such a nuub and thanx for the great resource.

**Comment by willrstern** [comment]
Ah, sorry I missed this to begin with!

**Comment by nikrb** [comment]
glad you did dude ... I mean I'm new to react but still, quite emabarrassing for me

**Comment by willrstern** [comment]
Never thought it to be embarrassing!  Happens to everyone.
