### ISSUE TITLE
`className` should be used instead of `class`

### ISSUE THREAD

**Issue by idmontie** [learncodeacademy/react-js-tutorials#2]
Your HTML should be using `className="container"` instead of `class="container"`

For example [this file](https://github.com/learncodeacademy/react-js-tutorials/blob/master/2-react-router/src/js/pages/Layout.js) should be using `className` instead of `class`.

`class` will throw warnings in the console when using it.

See [Tags and Attributes](https://facebook.github.io/react/docs/tags-and-attributes.html) in the React docs.

> All attributes are camel-cased and the attributes class and for are className and htmlFor, respectively, to match the DOM API specification.

**Comment by makaveliix16** [comment]
Will mentioned in his latest video that he's using a plugin(i.e. [babel-plugin-html-attrs](https://github.com/insin/babel-plugin-react-html-attrs)) to handle the transformation from `class` to `className` in the html code.

See [package.json file](https://github.com/learncodeacademy/react-js-tutorials/blob/master/package.json)

**Comment by idmontie** [comment]
Oh alright, I missed that. Closing.

**Comment by willrstern** [comment]
Yeah, I like using that plugin, because it makes it a lot less painful to paste stuff from around the web.
