### ISSUE TITLE
@connect unexpected token

### ISSUE THREAD

**Issue by polyakoff** [learncodeacademy/react-js-tutorials#24]
Following the part 5 of the tutorial, got this problem;

```
Syntax error: MyFile.js: Unexpected token (9:0)
>  9 | @connect((store) => {
```
Also confirmed [here](http://howtodevelop.eu/question/n-a,31617)

caused by `Layout.js`

**Comment by polyakoff** [comment]
fixed by

```
class Layout extends Component {

  componentWillMount() {
    <...>
  }

  render() {
    <...>
  }
}


function mapState (state) {
  return { <...> }
}

Layout = connect(mapState)(Layout);

export default Layout;
```

Can create a pull request with the fix if needed.

**Comment by willrstern** [comment]
@polyakoff that would mean that you're not transforming decorators.  Do you have the `babel-plugin-transform-decorators-legacy` npm package installed and in your webpack config, is your babel-loader using this plugin `transform-decorators-legacy`?

**Comment by polyakoff** [comment]
That was actually my fault, misconfigured environment indeed. I was using `npm start` to run the server, without webpack itself. Thanks, Will.

**Comment by Akumar96** [comment]
can you use yarn instead of npm? I have a similar problem where @connect doesn't work for me and shoots out the error: 
Syntax error: Unexpected token (70:0)
70 | @connect((store)

How did you configure your environment?
