### ISSUE TITLE
Where do you dispatch FETCH_TWEETS?

### ISSUE THREAD

**Issue by tsmith123** [learncodeacademy/react-js-tutorials#46]
Hey
Firstly thanks for your series on YT - very useful for learning the basics.
Trying to get a loader/spinner showing in the UI but I can't see where FETCH_TWEETS is dispatched to update `fetching` to `true`.

Sorry, this isn't an "issue" as such - more a question.

Thanks

**Comment by willrstern** [comment]
Hi there,

Ah, FETCH_TWEETS isn't currently being dispatched! I added it here:
https://github.com/learncodeacademy/react-js-tutorials/blob/master/5-redux-react/src/js/actions/tweetsActions.js#L5
