### ISSUE TITLE
Cannot get mobx #1 tutorial to work; exception

### ISSUE THREAD

**Issue by mikeyfev1** [learncodeacademy/react-js-tutorials#48]
Hello, thank you for the wonderful tutorials! I am trying to work my way through the mobx #1 tutorial and I am having problems. The store object (defined as a TodoStore) is not getting defined correctly. Here is my **TodoStore.js** file; it is **very** close to identical (I added some labels in the console.log calls) to yours in the video at 4:30:

> import { autorun, observable } from "mobx"
> 
> class TodoStore {
>   @observable todos = ["buy milk", "buy eggs"]
>   @observable filter = ""
> }
> 
> var store = window.store = new TodoStore
> 
> export default store
> 
> autorun(() => {
>   console.log("Filter: " + store.filter)
>   console.log("First item: " + store.todos[0])
> })

(Sorry, indentation doesn't come out quite right). When I render the HTML, my console window shows:

> Filter: undefined
> mobx.module.js:2955 [mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Autorun@1] TypeError: Cannot read property '0' of undefined
>     at TodoStore.js:14

I can change the value of **store.filter** with a console assignment, but I cannot assign, inspect, or reference in any way **store.todos[0]**:

> store.todos[0]
> VM424:1 Uncaught TypeError: Cannot read property '0' of undefined
>     at <anonymous>:1:12

Whereas I cannot find anything different between the code in the video at 4:30 (which is not the final checked-in version of the code) and my code, I am the pupil here and I'm sure I have something incorrect. Do you have any advice for me concerning how I might fix this? I am using:

> "babel-core": "^6.25.0",
>     "babel-loader": "^7.1.0",
>     "babel-plugin-add-module-exports": "^0.2.1",
>     "babel-plugin-react-html-attrs": "^2.0.0",
>     "babel-plugin-transform-class-properties": "^6.24.1",
>     "babel-plugin-transform-decorators-legacy": "^1.3.4",
>     "babel-preset-es2015": "^6.24.1",
>     "babel-preset-react": "^6.24.1",
>     "babel-preset-stage-0": "^6.24.1",
>     "mobx": "^3.1.16",
>     "mobx-react": "^4.2.1",
>     "react": "^15.6.1",
>     "react-dom": "^15.6.1",
>     "webpack": "^3.0.0",
>     "webpack-dev-server": "^2.5.0"

Thanks for any help you can provide.

**Comment by Hookkid** [comment]
Hey man... 

i believe that the variable `store` u created is not readily accessible inside autorun. have you tried using 
`this` as in `this.store.filter[0]`?

**Comment by mikeyfev1** [comment]
I was just following what the video does. And if you notice, the store object is available in the autorun; I make 2 console.log calls, one for filter and another for todos[0].  The filer call works fine.

**Comment by willrstern** [comment]
@mikeyfev1 your code is right (exactly what I'm doing in the video).  I'm thinking it might be your transpiler config?  What does your .babelrc file look like?

**Comment by mikeyfev1** [comment]
Yes, I have removed the @observeable attribute from the components of the TodoStore and everything appears. That tells me that the application of the mobX decorators are the problem.

You videos are wonderful, but I don't know anything about a .babelrc file. I know you briefly showed one, I saw the contents which looked very similar to parts of my webpack.config.js file. I assumed that webpack would take care of this. So my direct answer is that I don't have a .babelrc file and that I don't know what it is used for. Thank you for taking the time to answer me.

**Comment by mikeyfev1** [comment]
Here is the relevant section of my webpack.config.js file. I reproduced it from your excellent video series on react:
```
  module: {
    loaders: [{
      test: /\.js?$/,
      exclude: /(node_modules|bower_components)/,
      loader: 'babel-loader',
      query: {
        presets: ['react', 'es2015', 'stage-0'],
        plugins: ['react-html-attrs', 'transform-class-properties', 'transform-decorators-legacy']
      }
    }]
  }
```

**Comment by willrstern** [comment]
I'm not sure at this point, but it's something outside of your MobX code.  

I tried this:
- fresh clone of the repo
- go into the 6-mobx folder and `npm install && npm start`
- comment out the last line of `main.js` and paste your code into `TodoStore.js`
Everything's working as expected.

**Comment by willrstern** [comment]
And thanks as well @mikeyfev1!  Glad the series helped!

**Comment by mikeyfev1** [comment]
Yes, thank you.  Starting over from checked-in code got it working correctly.

And I learned about **yarn** accidentally while on the LearnCodeAcademy site. Another thanks!

**Comment by willrstern** [comment]
Hah, nice!
