### ISSUE TITLE
node_modules not present inside every react tutorial folders

### ISSUE THREAD

**Issue by CH3T** [learncodeacademy/react-js-tutorials#49]
node_modules are not found inside every folder for this tutorial for eg: 2-react-router, 3-flux etc. 

So should I grab it each time and install a fresh copy in each of the folders when I want to run those respective tutorials?

Is there a way I can link my systemwide npm to these tutorials?

**Comment by willrstern** [comment]
Each folder is it's own distinct project, so you'll need to `cd` into each folder and run `npm install`.  Then everything should work just fine!
