### ISSUE TITLE
"npm run dev" not working

### ISSUE THREAD

**Issue by werwuifi** [learncodeacademy/react-js-tutorials#6]
Hi,
I am new to react and wanted to run the first (basic react) example. I did "npm install" but on "npm run dev" I get a list of missing dependencies (one after the other) like mime, destroy, unpipe, statuses, http-errors, etc.
Am I supposed to install all these libs or what am I doing wrong?
Thx
w

**Comment by willrstern** [comment]
did you run `npm install` in each of the project folders?  If not, that's probably the issue.  each folder is considered it's own project.  I'll remove the package.json from the root level - that's leftover from when I started.

**Comment by werwuifi** [comment]
seems to work now, thought I run it from the project folders ... strange but seems to be my mistake. thx!

**Comment by willrstern** [comment]
Great to hear!
