### ISSUE TITLE
Some warning while compiling, running in Windows

### ISSUE THREAD

**Issue by FateRiddle** [learncodeacademy/react-js-tutorials#9]
client.min.js from UglifyJs
Condition always true [../~/.npminstall/react/0.14.8/react/lib/ReactMount.js:764,0]
Condition left of && always true [../~/.npminstall/json3/3.3.2/json3/lib/json3.js:5,0]
Condition always true [../~/.npminstall/react/0.14.8/react/lib/findDOMNode.js:46,0]
Condition always true [../~/.npminstall/react/0.14.8/react/lib/instantiateReactComponent.js:80,0]
Dropping unreachable code [../~/.npminstall/react/0.14.8/react/lib/shouldUpdateReactComponent.js:40,0]
Condition always true [../~/.npminstall/react/0.14.8/react/lib/traverseAllChildren.js:158,0]
Side effects in initialization of unused variable text [./js/reducers/tweetsReducer.js:30,20]
Condition always true [../~/.npminstall/punycode/1.3.2/punycode/punycode.js:511,0]
Dropping unreachable code [../~/.npminstall/punycode/1.3.2/punycode/punycode.js:518,2]
Side effects in initialization of unused variable freeExports [../~/.npminstall/punycode/1.3.2/punycode/punycode.js:5,0]
Side effects in initialization of unused variable freeModule [../~/.npminstall/punycode/1.3.2/punycode/punycode.js:7,0]
Dropping unused variable key [../~/.npminstall/punycode/1.3.2/punycode/punycode.js:56,0]
Condition always true [../~/.npminstall/react/0.14.8/react/lib/ReactDOMComponent.js:907,0]
Dropping side-effect-free statement [../~/.npminstall/react/0.14.8/react/lib/ReactEventListener.js:72,0]
Dropping unused function handleTopLevelWithPath [../~/.npminstall/react/0.14.8/react/lib/ReactEventListener.js:98,0]
Dropping unused variable DOCUMENT_FRAGMENT_NODE_TYPE [../~/.npminstall/react/0.14.8/react/lib/ReactEventListener.js:26,0]
Condition always true [../~/.npminstall/webpack-dev-server/1.14.1/webpack-dev-server/client?http:/localhost:8080:9,0]
Side effects in initialization of unused variable scriptHost [../~/.npminstall/webpack-dev-server/1.14.1/webpack-dev-server/client?http:/localhost:8080:5,0]
Condition always true [../~/.npminstall/webpack/1.13.1/webpack/hot/dev-server.js:6,0]
Dropping unreachable code [../~/.npminstall/webpack/1.13.1/webpack/hot/dev-server.js:62,0]

Happens when I run your example on Windows 7(no warning on Mac). Everything is still working though. Why?

**Comment by willrstern** [comment]
those `condition always true` errors are a result of code like this line:
https://github.com/facebook/react/blob/1a0e3a32150468223d6f9fd0125db0f8503b76d6/src/renderers/dom/client/ReactMount.js#L705

Which compiles for development mode by replacing `__DEV__` with `true` so webpack sees `if(true)` and warns you that it _appears_ the if statement is pointless, or might have a bug, since it will always run.
